<a href="https://colab.research.google.com/github/Kuoz2/tarea_repositorio/blob/main/class_5_poke_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔹 Mini-ejercicio 1

1. Carga `data/pokemon.csv` en un DataFrame llamado `df`
2. Imprime el shape
3. Crear una nueva tabla con Pokemon Legendarios
4. Crear una nueva tabla con solo las columnas `Name`, `Type 1`, `HP`, `Attack`, `Defense`, `Speed` de los primeros 10 pokémon
5. Crear 3 reglas para encontrar pokemon poderosos.

In [ ]:
import pandas as pd

## All the dataset

In [ ]:
pokedex = pd.read_csv('/content/pokemon.csv')
pokedex

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Shape

In [ ]:
pokedex.shape

(800, 13)

## Filtering legendaries

In [ ]:
filter = pokedex['Legendary'] == True
legendaries = pokedex[filter]
legendaries

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
156,144,Articuno,Ice,Flying,580,90,85,100,95,125,85,1,True
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
158,146,Moltres,Fire,Flying,580,90,100,90,125,85,90,1,True
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## First ten

In [ ]:
columnas_requeridas = ['Name', 'Type 1', 'HP', 'Attack', 'Defense', 'Speed']
result = pokedex[columnas_requeridas].head(10)
result
# resultado = pokedex.loc[:9, columnas_requeridas]
# resultado

                        Name Type 1  HP  Attack  Defense  Speed
0                  Bulbasaur  Grass  45      49       49     45
1                    Ivysaur  Grass  60      62       63     60
2                   Venusaur  Grass  80      82       83     80
3      VenusaurMega Venusaur  Grass  80     100      123     80
4                 Charmander   Fire  39      52       43     65
5                 Charmeleon   Fire  58      64       58     80
6                  Charizard   Fire  78      84       78    100
7  CharizardMega Charizard X   Fire  78     130      111    100
8  CharizardMega Charizard Y   Fire  78     104       78    100
9                   Squirtle  Water  44      48       65     43

## Powerful Pokemons

In [ ]:
filter1 = pokedex['Attack'] > 100
filter2 = pokedex['Defense'] > 100
filter3 = pokedex['Sp. Atk'] > 100
powerful = pokedex[filter1 & filter2 & filter3]
powerful.shape

(14, 13)

In [ ]:
powerful

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,700,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
538,481,Mesprit,Psychic,NaN,580,80,105,105,105,105,80,4,True
540,483,Dialga,Steel,Dragon,680,100,120,120,150,100,90,4,True
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## Bonus try

In [ ]:
pokedex.sort_values("Total", ascending = False).head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
418,380,LatiasMega Latias,Dragon,Psychic,700,80,100,120,140,150,110,3,True
494,445,GarchompMega Garchomp,Dragon,Ground,700,108,170,115,120,95,92,4,False
413,376,MetagrossMega Metagross,Steel,Psychic,700,80,145,150,105,110,110,3,False
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True